version: '3'
services:
  mongo_cs1:
    image: mongo
    container_name: mongo_cs1
    networks:
      mongo:
        ipv4_address: 172.20.0.12
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/config01/db:/data/db
      - ./data/config01/configdb:/data/configdb
      - ./data/config01/backup:/data/backup
    ports:
      - 27019:27019
    command: --configsvr --replSet "rs_configsvr" --bind_ip_all
    restart: always
  mongo_cs2:
    image: mongo
    container_name: mongo_cs2
    networks:
      mongo:
        ipv4_address: 172.20.0.13
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/config02/db:/data/db
      - ./data/config02/configdb:/data/configdb
      - ./data/config02/backup:/data/backup
    ports:
      - 27029:27019
    command: --configsvr --replSet "rs_configsvr" --bind_ip_all
    restart: always
  mongo_cs3:
    image: mongo
    container_name: mongo_cs3
    networks:
      mongo:
        ipv4_address: 172.20.0.14
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/config03/db:/data/db
      - ./data/config03/configdb:/data/configdb
      - ./data/config03/backup:/data/backup
    ports:
      - 27039:27019
    command: --configsvr --replSet "rs_configsvr" --bind_ip_all
    restart: always

  mongo_sh01:
    image: mongo
    container_name: mongo_sh01
    networks:
      mongo:
        ipv4_address: 172.20.0.15
    ports:
      - 27018:27018
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/shard01/db:/data/db
      - ./data/shard01/configdb:/data/configdb
      - ./data/shard01/backup:/data/backup
    command: --shardsvr --replSet "rs_shardsvr0" --bind_ip_all
    restart: always
    depends_on:
      - mongo_cs1
      - mongo_cs2
      - mongo_cs3
  mongo_sh02:
    image: mongo
    container_name: mongo_sh02
    networks:
      mongo:
        ipv4_address: 172.20.0.16
    ports:
      - 27028:27018
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/shard02/db:/data/db
      - ./data/shard02/configdb:/data/configdb
      - ./data/shard02/backup:/data/backup
    command: --shardsvr --replSet "rs_shardsvr0" --bind_ip_all
    restart: always
    depends_on:
      - mongo_cs1
      - mongo_cs2
      - mongo_cs3

  mongo_sh11:
    image: mongo
    container_name: mongo_sh11
    networks:
      mongo:
        ipv4_address: 172.20.0.17
    ports:
      - 27038:27018
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/shard11/db:/data/db
      - ./data/shard11/configdb:/data/configdb
      - ./data/shard11/backup:/data/backup
    command: --shardsvr --replSet "rs_shardsvr1" --bind_ip_all
    restart: always
    depends_on:
      - mongo_cs1
      - mongo_cs2
      - mongo_cs3
  mongo_sh12:
    image: mongo
    container_name: mongo_sh12
    networks:
      mongo:
        ipv4_address: 172.20.0.18
    ports:
      - 27048:27018
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/shard12/db:/data/db
      - ./data/shard12/configdb:/data/configdb
      - ./data/shard12/backup:/data/backup
    command: --shardsvr --replSet "rs_shardsvr1" --bind_ip_all
    restart: always
    depends_on:
      - mongo_cs1
      - mongo_cs2
      - mongo_cs3


  mongos:
    image: mongo
    container_name: mongos
    networks:
      mongo:
        ipv4_address: 172.20.0.11
    ports:
      - 27017:27017
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/mongos/db:/data/db
      - ./data/mongos/configdb:/data/configdb
    entrypoint: mongos
    command: --configdb rs_configsvr/172.20.0.12:27019,172.20.0.13:27019,172.20.0.14:27019 --bind_ip_all
    restart: always
    depends_on:
        - mongo_sh01
        - mongo_sh02
        - mongo_sh11
        - mongo_sh12

networks:
  mongo:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.10/24
