version: "2.2"
services:
  namenode:
    image: tyrival/hadoop-namenode:2.7.4
    container_name: namenode
    volumes:
      - ./namenode:/hadoop/dfs/name
      - ./input_files:/input_files
    ports:
      - 50070:50070
      - 8020:8020
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env

  resourcemanager:
    image: tyrival/hadoop-resourcemanager:2.7.4
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - hadoop.env

  historyserver:
    image: tyrival/hadoop-historyserver:2.7.4
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - ./historyserver:/hadoop/yarn/timeline
    env_file:
      - hadoop.env

  nodemanager1:
    image: tyrival/hadoop-nodemanager:2.7.4
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - hadoop.env

  datanode1:
    image: tyrival/hadoop-datanode:2.7.4
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - ./datanode1:/hadoop/dfs/data
    env_file:
      - hadoop.env

  datanode2:
    image: tyrival/hadoop-datanode:2.7.4
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - ./datanode2:/hadoop/dfs/data
    env_file:
      - hadoop.env

  datanode3:
    image: tyrival/hadoop-datanode:2.7.4
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - ./datanode3:/hadoop/dfs/data
    env_file:
      - hadoop.env

  master:
    image: gettyimages/spark:2.4.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    container_name: master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    links:
      - namenode
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  worker:
    image: gettyimages/spark:2.4.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    container_name: worker
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    links:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 9013
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
      
volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:

