version: '2'

services:
  zoo1:
    image: tyrival/zookeeper:3.4.13
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181

  zoo2:
    image: tyrival/zookeeper:3.4.13
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181

  zoo3:
    image: tyrival/zookeeper:3.4.13
    restart: always
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181

  kafka1:
    image: tyrival/kafka:2.1.1
    restart: always
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.55
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.55:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka1/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    image: tyrival/kafka:2.1.1
    restart: always
    container_name: kafka2
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.55
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.55:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    volumes:
      - ./kafka2/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3

  kafka3:
    image: tyrival/kafka:2.1.1
    restart: always
    container_name: kafka3
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.55
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.55:9094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:904
    volumes:
      - ./kafka3/docker.sock:/var/run/docker.sock
    external_links:
      - zoo1
      - zoo2
      - zoo3