version: "3"
services:
  redis1:
    container_name: redis1
    image: redis:5.0.7
    ports:
      - 7001:7001
      - 17001:17001
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7001.conf:/usr/local/etc/redis/redis.conf
      - ./7001/logs:/usr/local/redis/logs
      - ./7001/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7001", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7001"]
    restart: always

  redis2:
    container_name: redis2
    image: redis:5.0.7
    ports:
      - 7002:7002
      - 17002:17002
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7002.conf:/usr/local/etc/redis/redis.conf
      - ./7002/logs:/usr/local/redis/logs
      - ./7002/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7002", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7002"]
    restart: always

  redis3:
    container_name: redis3
    image: redis:5.0.7
    ports:
      - 7003:7003
      - 17003:17003
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7003.conf:/usr/local/etc/redis/redis.conf
      - ./7003/logs:/usr/local/redis/logs
      - ./7003/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7003", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7003"]
    restart: always

  redis4:
    container_name: redis4
    image: redis:5.0.7
    ports:
      - 7004:7004
      - 17004:17004
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7004.conf:/usr/local/etc/redis/redis.conf
      - ./7004/logs:/usr/local/redis/logs
      - ./7004/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7004", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7004"]
    restart: always

  redis5:
    container_name: redis5
    image: redis:5.0.7
    ports:
      - 7005:7005
      - 17005:17005
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7005.conf:/usr/local/etc/redis/redis.conf
      - ./7005/logs:/usr/local/redis/logs
      - ./7005/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7005", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7005"]
    restart: always

  redis6:
    container_name: redis6
    image: redis:5.0.7
    ports:
      - 7006:7006
      - 17006:17006
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/redis-7006.conf:/usr/local/etc/redis/redis.conf
      - ./7006/logs:/usr/local/redis/logs
      - ./7006/data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", --port,"7006", --cluster-announce-ip,"${ip}", --cluster-announce-port,"7006"]
    restart: always

  redis-cluster-creator:
    image: redis:5.0.7
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli -a 123456 --cluster create ${ip}:7001 ${ip}:7002 ${ip}:7003 ${ip}:7004 ${ip}:7005 ${ip}:7006 --cluster-replicas 1']
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6